name: Deployment pipeline

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: heroku deployment 
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bloglist-242'
          heroku_email: 'lahtinen.jaakko@gmail.com'
          healthcheck: "https://bloglist-242.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          appdir: "backend"