name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_prerequisites:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install on backend
        run: |
            cd backend
            npm install 
      - name: npm install on frontend
        run: |
            cd frontend
            npm install
      - name: lint backend
        run: |
            cd backend
            npm run eslint
      - name: lint frontend
        run: |
            cd frontend
            npm install
      - name: build frontend
        run: |
          cd frontend
          npm run build
      - name: test backend
        run: |
          cd backend
          npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} 
          SECRET: ${{ secrets.SECRET }}
      - name: test frontend
        run: |
          cd frontend
          npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} 
          SECRET: ${{ secrets.SECRET }}
  deploy:
    needs: deployment_prerequisites
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: backend heroku deployment 
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bloglist-242'
          heroku_email: 'lahtinen.jaakko@gmail.com'
          healthcheck: "https://bloglist-242.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          appdir: "backend" # <- This will point to the api folder in your project