name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install on backend
        run: |
            cd backend
            npm install 
      - name: npm install on frontend
        run: |
            cd ..
            cd frontend
            npm install
      - name: lint backend
        run: |
            cd backend
            npm run eslint
      - name: lint frontend
        run: |
            cd ..
            cd frontend
            npm install
      - name: build
        run: |
          npm run build
          cd frontend
          npm install
      - name: test
        run: npm run test
      - name: e2e tests 
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
  deploy:
    if: ${{github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    needs: simple_deployment_pipeline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Conditions event name is push
        run: echo ${{github.event_name == 'push'}}
      - name: Commit messages contains skip
        run: echo ${{ contains(join(github.event.commits.*.message), '#skip') }}
      - name: heroku deployment 
        uses: akhileshns/heroku-deploy@v3.8.9
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bloglist-242'
          heroku_email: 'lahtinen.jaakko@gmail.com'
          healthcheck: "https://bloglist-242.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true