name: Test pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_prerequisites:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install on backend
        run: |
            cd backend
            npm install 
      - name: npm install on frontend
        run: |
            cd frontend
            npm install
      - name: lint backend
        run: |
            cd backend
            npm run eslint
      - name: lint frontend
        run: |
            cd frontend
            npm install
      - name: build frontend
        run: |
          cd frontend
          npm run build
      - name: test backend
        run: |
          cd backend
          npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} 
          SECRET: ${{ secrets.SECRET }}
      - name: test frontend
        run: |
          cd frontend
          npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} 
          SECRET: ${{ secrets.SECRET }}
  uibuild:
    needs: deployment_prerequisites
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create UI Build
      run: |
            cd backend
            npm run build:ui
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "UI Build" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}